"""Agent task cards: self-contained prompts for Claude Code sub-agents.

Phase 2 of the dispatch layer. Each task card contains everything a Claude
Code Agent needs to do real generative work:
  - Full context (step number, file paths, current content analysis)
  - Specific instructions (what to write, how much, what style)
  - Acceptance criteria (word count, theorem count, test count)
  - Session type transitions to emit on completion

Task cards are generated by analyzing gaps via the evaluator, then handed
to Claude Code's Agent tool for execution.

Architecture:
    Evaluator → gap analysis → TaskCard → Claude Code Agent → files on disk
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Task card data type
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class TaskCard:
    """A self-contained task for a Claude Code sub-agent."""
    agent_type: str
    step_number: str
    action: str            # "expand_paper", "create_proofs", "write_module", etc.
    prompt: str            # full prompt for the Agent tool
    context_files: tuple[str, ...] = ()   # files the agent should read
    output_files: tuple[str, ...] = ()    # files the agent should create/edit
    acceptance_criteria: tuple[str, ...] = ()
    transitions: tuple[str, ...] = ()     # session type transitions
    priority: int = 1      # 1=highest, 3=lowest
    metadata: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Project root
# ---------------------------------------------------------------------------

def _find_root() -> Path:
    for candidate in [Path.cwd(), Path.cwd().parent, Path(__file__).parent.parent.parent]:
        if (candidate / "papers" / "steps").is_dir():
            return candidate
    return Path.cwd()


def _module_path(module_name: str) -> Path:
    """Find a module .py file, handling both repo root and reticulate/ CWD."""
    # Try standard path first
    p = _ROOT / "reticulate" / "reticulate" / f"{module_name}.py"
    if p.exists():
        return p
    # If _ROOT is already the reticulate/ subdir
    p2 = _ROOT / "reticulate" / f"{module_name}.py"
    if p2.exists():
        return p2
    return p  # Return standard (will be checked for existence by caller)


_ROOT = _find_root()


def _step_dir(step_number: str) -> Path | None:
    steps_dir = _ROOT / "papers" / "steps"
    if not steps_dir.is_dir():
        return None
    for d in steps_dir.iterdir():
        if d.is_dir() and d.name.startswith(f"step{step_number}-"):
            return d
    return None


def _step_title(step_number: str) -> str:
    sdir = _step_dir(step_number)
    if sdir is None:
        return "Unknown"
    return sdir.name.replace(f"step{step_number}-", "").replace("-", " ").title()


def _read_file(path: Path) -> str:
    if path.exists():
        return path.read_text(errors="replace")
    return ""


def _word_count(text: str) -> int:
    return len(text.split())


def _count_sections(text: str) -> list[str]:
    """Extract LaTeX section titles."""
    return re.findall(r"\\section\{([^}]+)\}", text)


def _find_thin_section(text: str) -> str | None:
    """Find the section with the fewest words."""
    sections = re.split(r"\\section\{[^}]+\}", text)
    if len(sections) <= 1:
        return None
    section_titles = _count_sections(text)
    if not section_titles:
        return None
    min_words = float("inf")
    thin = None
    for title, body in zip(section_titles, sections[1:]):
        wc = _word_count(body)
        if wc < min_words:
            min_words = wc
            thin = title
    return thin


# ---------------------------------------------------------------------------
# Task card generators per agent type
# ---------------------------------------------------------------------------

def writer_task(step_number: str, fixes: list[str]) -> TaskCard | None:
    """Generate a Writer task card for expanding/creating a paper."""
    sdir = _step_dir(step_number)
    if sdir is None:
        return None

    title = _step_title(step_number)
    main_tex = sdir / "main.tex"
    text = _read_file(main_tex)
    wc = _word_count(text)
    sections = _count_sections(text)
    thin = _find_thin_section(text)

    # Determine what needs fixing
    needs_expansion = any("word count" in f.lower() or "words" in f.lower() for f in fixes)
    needs_structure = any("structure" in f.lower() or "conclusion" in f.lower() for f in fixes)
    needs_creation = not main_tex.exists()

    if needs_creation:
        action = "create_paper"
        words_needed = 5500
        prompt = f"""You are a Writer agent for the Session Types research programme.

TASK: Create an educational paper for Step {step_number}: {title}

Write a complete LaTeX paper with:
- \\documentclass{{article}} with amsmath, amsthm, amssymb
- Abstract (150-200 words)
- Introduction (explain the problem and contribution)
- Background (session types, lattices, relevant prior steps)
- Main content (3-4 sections with worked examples, formal definitions, benchmark data)
- Related Work
- Conclusion (summary + future work)
- Bibliography (10+ references using \\thebibliography)

Target: {words_needed}+ words. Use formal mathematical style with Definition/Theorem/Example environments.
Include at least 2 worked examples using real benchmark protocols (SMTP, OAuth, Iterator, etc.).

Output file: {main_tex}"""

    elif needs_expansion:
        words_needed = max(5500 - wc, 500)
        prompt = f"""You are a Writer agent for the Session Types research programme.

TASK: Expand the paper for Step {step_number}: {title}

Current word count: {wc} (target: 5000+, need {words_needed} more words)
Current sections: {', '.join(sections) if sections else '(none)'}
Thinnest section: {thin or '(unknown)'}

Read {main_tex} first, then expand by adding:
1. More worked examples with real benchmark protocols
2. Deeper explanations in the thinnest section ({thin})
3. Comparison tables or formal analysis where appropriate
4. Additional benchmark data from the 34 standard protocols

Do NOT restructure the paper. Add depth to existing sections.
Do NOT add placeholder text. Every sentence must be substantive.

Output file: {main_tex}"""

    elif needs_structure:
        prompt = f"""You are a Writer agent for the Session Types research programme.

TASK: Fix paper structure for Step {step_number}: {title}

Issues: {'; '.join(f for f in fixes if 'structure' in f.lower() or 'conclusion' in f.lower())}

Read {main_tex} and add the missing structural elements:
- If missing abstract: add \\begin{{abstract}}...\\end{{abstract}}
- If missing conclusion: add \\section{{Conclusion}} with summary + future work
- If missing bibliography: add \\begin{{thebibliography}} with 10+ references
- If missing introduction: add \\section{{Introduction}}

Output file: {main_tex}"""
    else:
        return None

    return TaskCard(
        agent_type="Writer",
        step_number=step_number,
        action=action if needs_creation else "expand_paper" if needs_expansion else "fix_structure",
        prompt=prompt,
        context_files=(str(main_tex),),
        output_files=(str(main_tex),),
        acceptance_criteria=(
            f"Word count >= 5000 (currently {wc})",
            "Has abstract, introduction, conclusion, bibliography",
            "Contains worked examples with benchmark protocols",
        ),
        transitions=("writePaper", "paperReady"),
        priority=2 if needs_expansion else 1,
    )


def prover_task(step_number: str, fixes: list[str]) -> TaskCard | None:
    """Generate a Prover task card for creating/expanding proofs."""
    sdir = _step_dir(step_number)
    if sdir is None:
        return None

    title = _step_title(step_number)
    proofs_tex = sdir / "proofs.tex"
    main_tex = sdir / "main.tex"
    proofs_text = _read_file(proofs_tex)
    main_text = _read_file(main_tex)
    proofs_wc = _word_count(proofs_text)

    needs_creation = not proofs_tex.exists()
    needs_expansion = any("thin" in f.lower() or "stub" in f.lower() for f in fixes)

    if not needs_creation and not needs_expansion:
        # Check if any fix mentions proofs
        if not any("proof" in f.lower() for f in fixes):
            return None

    # Extract key results from main.tex to formalize
    theorems_in_main = re.findall(r"\\begin\{(theorem|proposition|lemma)\}(.*?)\\end\{\1\}",
                                   main_text, re.DOTALL)
    definitions_in_main = re.findall(r"\\begin\{definition\}(.*?)\\end\{definition\}",
                                      main_text, re.DOTALL)

    if needs_creation:
        prompt = f"""You are a Prover agent for the Session Types research programme.

TASK: Create companion proofs document for Step {step_number}: {title}

Read {main_tex} first to identify the key results that need formal proofs.

Create {proofs_tex} with:
- \\documentclass{{article}} with amsmath, amsthm, amssymb
- Title: "Companion Proofs: {title}"
- 3+ formal theorems with complete proofs
- Use standard LaTeX theorem environments (theorem, proposition, lemma, proof)
- Include definitions that formalize the main concepts
- Cross-reference the step paper

The proofs should be rigorous but accessible. Use natural-language proof style
(not Lean/Coq syntax). Target 1200+ words.

Found in main.tex: {len(theorems_in_main)} theorem-like environments, {len(definitions_in_main)} definitions.

Output file: {proofs_tex}"""
    else:
        prompt = f"""You are a Prover agent for the Session Types research programme.

TASK: Expand companion proofs for Step {step_number}: {title}

Current proofs.tex: {proofs_wc} words (target: 1200+)

Read {proofs_tex} and {main_tex}, then expand by:
1. Adding 1-2 new propositions that formalize key claims from the paper
2. Deepening existing proofs with more detail
3. Adding corollaries that connect to other steps

Target: 1200+ words, 3+ theorem-like environments.

Output file: {proofs_tex}"""

    return TaskCard(
        agent_type="Prover",
        step_number=step_number,
        action="create_proofs" if needs_creation else "expand_proofs",
        prompt=prompt,
        context_files=(str(main_tex), str(proofs_tex)),
        output_files=(str(proofs_tex),),
        acceptance_criteria=(
            "1200+ words",
            "3+ theorem/proposition/lemma environments",
            "Complete proofs (not stubs)",
        ),
        transitions=("writeProofs", "proofsReady"),
        priority=2,
    )


def implementer_task(step_number: str, fixes: list[str], module_name: str | None = None) -> TaskCard | None:
    """Generate an Implementer task card for creating a module."""
    if module_name is None:
        from reticulate.evaluator import _MODULE_MAP
        module_name = _MODULE_MAP.get(step_number)

    if not module_name:
        return None  # Paper-only step

    mod_path = _module_path(module_name)
    if mod_path.exists():
        text = _read_file(mod_path)
        if len(text.split("\n")) >= 100:
            return None  # Module is substantial

    title = _step_title(step_number)
    sdir = _step_dir(step_number)
    main_tex = sdir / "main.tex" if sdir else None

    prompt = f"""You are an Implementer agent for the Session Types research programme.

TASK: {'Create' if not mod_path.exists() else 'Expand'} module {module_name}.py for Step {step_number}: {title}

{'Read ' + str(main_tex) + ' for context on what this module should implement.' if main_tex and main_tex.exists() else ''}

Requirements:
- Python 3.11+, type hints on all functions
- Use dataclasses/NamedTuple for data types
- Pure functions where possible (deterministic, no side effects)
- Use standard library only (no external dependencies)
- Module docstring explaining purpose and usage
- 100+ lines, 3+ public functions

Read existing code in reticulate/reticulate/ for style reference (parser.py, lattice.py).

Output file: {mod_path}"""

    return TaskCard(
        agent_type="Implementer",
        step_number=step_number,
        action="create_module" if not mod_path.exists() else "expand_module",
        prompt=prompt,
        context_files=(str(main_tex),) if main_tex else (),
        output_files=(str(mod_path),),
        acceptance_criteria=(
            "100+ lines",
            "3+ public functions",
            "Type hints on all functions",
            "Module docstring",
        ),
        transitions=("implement", "moduleReady"),
        priority=1,
    )


def tester_task(step_number: str, fixes: list[str], module_name: str | None = None) -> TaskCard | None:
    """Generate a Tester task card for creating tests."""
    if module_name is None:
        from reticulate.evaluator import _MODULE_MAP
        module_name = _MODULE_MAP.get(step_number)

    if not module_name:
        return None  # Paper-only step

    # Handle both repo root and reticulate/ CWD
    test_path = _ROOT / "reticulate" / "tests" / f"test_{module_name}.py"
    if not test_path.exists():
        test_path = _ROOT / "tests" / f"test_{module_name}.py"
    mod_path = _module_path(module_name)

    if test_path.exists():
        text = _read_file(test_path)
        test_count = text.count("def test_")
        if test_count >= 20:
            return None  # Tests are sufficient

    title = _step_title(step_number)

    prompt = f"""You are a Tester agent for the Session Types research programme.

TASK: {'Create' if not test_path.exists() else 'Expand'} test suite for Step {step_number}: {title}

Module: {mod_path}
Test file: {test_path}

Read {mod_path} first, then {'create' if not test_path.exists() else 'expand'} {test_path} with:
- pytest-style tests (no unittest.TestCase needed, but ok to use classes)
- 20+ test functions covering:
  - Normal cases (valid inputs)
  - Edge cases (empty, boundary values)
  - Error cases (invalid inputs)
  - Property-based checks where applicable
- Import from reticulate.{module_name}
- Each test function named test_* with a clear purpose

Read existing tests in reticulate/tests/ for style reference.

Output file: {test_path}"""

    return TaskCard(
        agent_type="Tester",
        step_number=step_number,
        action="create_tests" if not test_path.exists() else "expand_tests",
        prompt=prompt,
        context_files=(str(mod_path),),
        output_files=(str(test_path),),
        acceptance_criteria=(
            "20+ test functions",
            "All tests pass",
            "Covers normal, edge, and error cases",
        ),
        transitions=("writeTests", "testsPass"),
        priority=1,
    )


# ---------------------------------------------------------------------------
# Generate all task cards for a step
# ---------------------------------------------------------------------------

def generate_task_cards(step_number: str) -> list[TaskCard]:
    """Analyze a step and generate all needed task cards.

    Uses the evaluator to find gaps, then creates appropriate task cards
    for each agent type that can fix those gaps.
    """
    from reticulate.evaluator import evaluate_step, _MODULE_MAP

    result = evaluate_step(step_number, run_tests=False)

    if result.accepted:
        return []  # Already A+, nothing to do

    fixes = list(result.fixes)
    module_name = _MODULE_MAP.get(step_number)
    cards: list[TaskCard] = []

    # Writer: paper expansion/creation/structure
    card = writer_task(step_number, fixes)
    if card:
        cards.append(card)

    # Prover: companion proofs
    card = prover_task(step_number, fixes)
    if card:
        cards.append(card)

    # Implementer: module creation/expansion
    card = implementer_task(step_number, fixes, module_name)
    if card:
        cards.append(card)

    # Tester: test creation/expansion
    card = tester_task(step_number, fixes, module_name)
    if card:
        cards.append(card)

    # Sort by priority
    cards.sort(key=lambda c: c.priority)
    return cards


def generate_sprint_cards(sprint_number: int = 1) -> dict[str, list[TaskCard]]:
    """Generate task cards for all steps that need work.

    Returns: {step_number: [TaskCard, ...]}
    """
    from reticulate.evaluator import evaluate_all

    results = evaluate_all(run_tests=False)
    failing = [r for r in results if not r.accepted]

    sprint_cards: dict[str, list[TaskCard]] = {}
    for result in failing:
        cards = generate_task_cards(result.step_number)
        if cards:
            sprint_cards[result.step_number] = cards

    return sprint_cards


def sprint_summary(cards: dict[str, list[TaskCard]]) -> str:
    """Human-readable summary of a sprint's task cards."""
    lines = [f"Sprint Task Cards: {sum(len(v) for v in cards.values())} tasks across {len(cards)} steps"]
    lines.append("")

    by_agent: dict[str, int] = {}
    by_action: dict[str, int] = {}
    for step, step_cards in sorted(cards.items()):
        lines.append(f"  Step {step}:")
        for card in step_cards:
            lines.append(f"    [{card.agent_type}] {card.action} (priority {card.priority})")
            by_agent[card.agent_type] = by_agent.get(card.agent_type, 0) + 1
            by_action[card.action] = by_action.get(card.action, 0) + 1

    lines.append("")
    lines.append("  By agent: " + ", ".join(f"{k}={v}" for k, v in sorted(by_agent.items())))
    lines.append("  By action: " + ", ".join(f"{k}={v}" for k, v in sorted(by_action.items())))
    return "\n".join(lines)
