"""Prime ideal spectrum Spec(L) of a session-type lattice (Step 363h).

Given a session type S with state space L(S), this module constructs the
prime ideal spectrum Spec(L(S)) along with the Zariski-style topology
generated by the basic open sets D(a) = {p in Spec(L) : a not in p}.

The construction works on the SCC quotient of the state space (so cycles
from recursive types are collapsed) and proceeds in three phases:

  1. Build a small in-memory representation of the finite lattice
     (carrier = SCC quotient nodes) with order, meet and join tables.
  2. Enumerate all order-ideals (downsets closed under finite joins).
     For finite lattices, an order-ideal is the same thing as a
     principal-or-finitely-generated downset that is closed under join,
     and there are at most 2^|L| of them.
  3. Filter ideals to keep the *prime* ones: an ideal I is prime iff
     I is proper (I != L) and  x ∧ y ∈ I  implies  x ∈ I  or  y ∈ I.

The Zariski-style topology on Spec(L) has as basic opens the sets

        D(a)  =  { p ∈ Spec(L) : a ∉ p },         a ∈ L,

and as closed sets V(a) = Spec(L) \\ D(a) = {p : a ∈ p}.  We expose both
the basic-open lattice and the topology generated by it.

Bidirectional morphisms (the contribution):

    phi : L  -->  Spec(L)        a |-->  D(a)             (Stone map)
    psi : Spec(L) --> L          p |-->  bigvee (L \\ p)  (top of complement)

For *distributive* L the pair (phi, psi) classifies as an order
isomorphism between L and the lattice of basic opens of Spec(L), and a
Galois connection between the powerset of Spec(L) and L.  For
non-distributive L, phi is still order-preserving and psi is still well
defined; we report which axioms hold and which fail.

PRACTICAL meaning of Spec(L):

  * Each prime ideal p ∈ Spec(L) names an *irreducible subprotocol*: the
    largest contiguous "prefix-region" of L that you can isolate from
    the rest without losing closure under joins.
  * D(a) is the set of subprotocol viewpoints in which the action a is
    *still possible* (a is "outside" the prefix p).
  * V(a) is the set of viewpoints in which a has been *consumed*.
  * Decomposition: a protocol decomposes into irreducible components iff
    Spec(L) is disconnected; the connected components are the maximal
    independent subprotocols.

This file is pure Python (no third-party dependencies) and is consumed
by the step paper papers/steps/step363h-prime-spectrum.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Iterable

if TYPE_CHECKING:
    from reticulate.statespace import StateSpace


# ---------------------------------------------------------------------------
# Internal lattice carrier
# ---------------------------------------------------------------------------

@dataclass
class _Lattice:
    """Self-contained finite lattice built from a state space's SCC quotient.

    Elements are integers 0..n-1 in the *quotient*.  The order is
    ``a <= b`` iff in the original state-space sense ``b`` reaches ``a``
    (i.e. ``a`` is "later" in the protocol; bottom = end state).
    """

    elements: tuple[int, ...]
    le: dict[tuple[int, int], bool]
    meet: dict[tuple[int, int], int]
    join: dict[tuple[int, int], int]
    top: int
    bottom: int
    rep: dict[int, int]                    # quotient idx -> representative orig state
    state_to_node: dict[int, int]          # original state -> quotient idx

    def is_le(self, a: int, b: int) -> bool:
        return self.le[(a, b)]

    def is_lt(self, a: int, b: int) -> bool:
        return a != b and self.le[(a, b)]


def _build_lattice(ss: StateSpace) -> _Lattice:
    """Build a self-contained _Lattice from a state space.

    Uses the existing lattice machinery to compute the SCC quotient and
    pairwise meets/joins, then materialises everything into dictionaries.
    Raises ValueError if the state space is not a lattice.
    """
    from reticulate.lattice import _build_quotient_poset, check_lattice  # noqa: WPS433

    lr = check_lattice(ss)
    if not lr.is_lattice:
        raise ValueError(
            f"state space is not a lattice: counterexample={lr.counterexample}"
        )

    q = _build_quotient_poset(ss)
    nodes = tuple(sorted(q.nodes))

    # Order: a <= b iff b reaches a   (because top reaches everything, top is greatest)
    le: dict[tuple[int, int], bool] = {}
    for a in nodes:
        for b in nodes:
            le[(a, b)] = a in q.fwd_reach[b]

    # Meets and joins via the existing helpers (they return quotient indices)
    from reticulate.lattice import _meet_on_quotient, _join_on_quotient  # noqa: WPS433

    meet: dict[tuple[int, int], int] = {}
    join: dict[tuple[int, int], int] = {}
    for a in nodes:
        for b in nodes:
            m = _meet_on_quotient(q, a, b)
            j = _join_on_quotient(q, a, b)
            if m is None or j is None:
                raise ValueError(
                    f"missing meet/join for ({a},{b}); not a lattice"
                )
            meet[(a, b)] = m
            join[(a, b)] = j

    return _Lattice(
        elements=nodes,
        le=le,
        meet=meet,
        join=join,
        top=q.top,
        bottom=q.bottom,
        rep=dict(q.rep),
        state_to_node=dict(q.state_to_node),
    )


# ---------------------------------------------------------------------------
# Public result types
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class PrimeIdeal:
    """A prime ideal of a finite lattice.

    Stored as a frozenset of quotient-node indices.  Includes a small bit
    of metadata: whether the ideal is principal (i.e. generated by a
    single element via the down-set operator) and the generator if so.
    """

    members: frozenset[int]
    is_principal: bool
    generator: int | None  # quotient-node index, or None if not principal

    def contains(self, element: int) -> bool:
        return element in self.members

    def __le__(self, other: "PrimeIdeal") -> bool:
        return self.members <= other.members


@dataclass(frozen=True)
class ZariskiTopology:
    """The Zariski-style topology on Spec(L).

    Stored as the family of *basic opens* D(a) for each lattice element a,
    plus the (closed) family V(a) = Spec(L) \\ D(a).  The full topology is
    generated by arbitrary unions and finite intersections of basic opens;
    for finite lattices the basic opens are already closed under finite
    intersection (D(a) ∩ D(b) = D(a ∧ b)) and union of D(a) ∪ D(b)
    contains D(a ∨ b), so the basic-open family forms a sub-lattice of the
    topology and we expose it directly.
    """

    primes: tuple[PrimeIdeal, ...]
    basic_opens: dict[int, frozenset[int]]   # element -> indices into `primes`
    closed_sets: dict[int, frozenset[int]]   # V(a)

    @property
    def num_points(self) -> int:
        return len(self.primes)

    def open_of(self, element: int) -> frozenset[int]:
        return self.basic_opens[element]

    def closed_of(self, element: int) -> frozenset[int]:
        return self.closed_sets[element]


@dataclass(frozen=True)
class SpectrumResult:
    """Full result of a Spec(L) computation."""

    is_lattice: bool
    is_distributive: bool
    num_elements: int
    num_ideals: int
    num_prime_ideals: int
    primes: tuple[PrimeIdeal, ...]
    topology: ZariskiTopology | None
    irreducible_components: tuple[frozenset[int], ...]
    phi_is_order_preserving: bool
    phi_is_injective: bool
    psi_is_well_defined: bool
    duality_holds: bool         # phi ∘ psi = id and psi ∘ phi = id
    notes: tuple[str, ...] = field(default_factory=tuple)

    @property
    def is_irreducible(self) -> bool:
        """A protocol is irreducible iff Spec(L) is connected."""
        return len(self.irreducible_components) <= 1


# ---------------------------------------------------------------------------
# Ideal / prime-ideal enumeration
# ---------------------------------------------------------------------------

def enumerate_ideals(L: _Lattice) -> list[frozenset[int]]:
    """Enumerate all order-ideals of *L*.

    An order-ideal is a downset closed under finite joins.  In a finite
    lattice every downset that contains 0 and is closed under binary join
    is automatically closed under all finite joins, so we only need to
    check the binary case.

    The enumeration walks the powerset of join-irreducibles, but for
    simplicity (and because the lattices we care about have at most a few
    dozen elements) we directly enumerate all subsets of L and filter.
    """
    elements = L.elements
    n = len(elements)
    ideals: list[frozenset[int]] = []
    for mask in range(1 << n):
        subset_list = [elements[i] for i in range(n) if mask & (1 << i)]
        subset = frozenset(subset_list)

        # By convention every ideal of a bounded lattice contains bottom
        # (in particular, the empty set is excluded).
        if L.bottom not in subset:
            continue

        # Downward closed: x in subset and y <= x implies y in subset
        ok = True
        for x in subset_list:
            for y in elements:
                if L.is_le(y, x) and y not in subset:
                    ok = False
                    break
            if not ok:
                break
        if not ok:
            continue

        # Closed under join
        join_closed = True
        for x in subset_list:
            for y in subset_list:
                if L.join[(x, y)] not in subset:
                    join_closed = False
                    break
            if not join_closed:
                break
        if not join_closed:
            continue

        ideals.append(subset)

    return ideals


def enumerate_prime_ideals(L: _Lattice) -> list[PrimeIdeal]:
    """Enumerate all prime ideals of *L*.

    Definition (finite lattice version):
      An ideal I is *prime* iff
        (a) I is proper (I != L), and
        (b) for all x, y in L: x ∧ y ∈ I implies x ∈ I or y ∈ I.
    """
    ideals = enumerate_ideals(L)
    primes: list[PrimeIdeal] = []
    full = frozenset(L.elements)
    for I in ideals:
        if I == full:
            continue
        if len(I) == 0:
            # Empty set: prime iff bottom is not the only element forced in.
            # In a bounded lattice with >1 element the empty set is NOT an ideal
            # (since by convention ideals contain bottom).  Skip.
            continue

        is_prime = True
        for x in L.elements:
            for y in L.elements:
                if L.meet[(x, y)] in I and x not in I and y not in I:
                    is_prime = False
                    break
            if not is_prime:
                break

        if not is_prime:
            continue

        # Detect principality: I = down(g) for some g in L
        generator: int | None = None
        for g in L.elements:
            down_g = frozenset(y for y in L.elements if L.is_le(y, g))
            if down_g == I:
                generator = g
                break

        primes.append(PrimeIdeal(
            members=I,
            is_principal=generator is not None,
            generator=generator,
        ))

    # Sort for determinism: by size then lexicographic
    primes.sort(key=lambda p: (len(p.members), sorted(p.members)))
    return primes


# ---------------------------------------------------------------------------
# Topology
# ---------------------------------------------------------------------------

def build_topology(
    L: _Lattice,
    primes: list[PrimeIdeal],
) -> ZariskiTopology:
    """Build the Zariski-style topology on Spec(L)."""
    full_idx = frozenset(range(len(primes)))
    basic_opens: dict[int, frozenset[int]] = {}
    closed_sets: dict[int, frozenset[int]] = {}
    for a in L.elements:
        opn = frozenset(i for i, p in enumerate(primes) if a not in p.members)
        basic_opens[a] = opn
        closed_sets[a] = full_idx - opn
    return ZariskiTopology(
        primes=tuple(primes),
        basic_opens=basic_opens,
        closed_sets=closed_sets,
    )


def irreducible_components(
    L: _Lattice,
    topology: ZariskiTopology,
) -> tuple[frozenset[int], ...]:
    """Connected components of Spec(L) under the Zariski topology.

    Two prime ideals p, q lie in the same component iff there is a chain
    p = p_0, p_1, ..., p_k = q with each consecutive pair sharing a basic
    open or sharing a closed set (equivalently: with non-empty common
    Zariski neighbourhood).  We compute components by union-find on the
    graph whose edges connect primes that co-belong to some non-trivial
    basic open D(a) with |D(a)| >= 2.
    """
    n = len(topology.primes)
    parent = list(range(n))

    def find(i: int) -> int:
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    def union(i: int, j: int) -> None:
        ri, rj = find(i), find(j)
        if ri != rj:
            parent[ri] = rj

    for a in L.elements:
        opn = topology.basic_opens[a]
        if len(opn) >= 2:
            ids = sorted(opn)
            base = ids[0]
            for k in ids[1:]:
                union(base, k)
        cls = topology.closed_sets[a]
        if len(cls) >= 2:
            ids = sorted(cls)
            base = ids[0]
            for k in ids[1:]:
                union(base, k)

    groups: dict[int, set[int]] = {}
    for i in range(n):
        groups.setdefault(find(i), set()).add(i)
    return tuple(frozenset(g) for g in groups.values())


# ---------------------------------------------------------------------------
# Bidirectional morphisms phi and psi
# ---------------------------------------------------------------------------

def phi_map(
    L: _Lattice,
    topology: ZariskiTopology,
) -> dict[int, frozenset[int]]:
    """phi : L --> Spec(L), phi(a) = D(a) = {p : a not in p}.

    Returns a dict from element to the set of prime indices comprising D(a).
    """
    return dict(topology.basic_opens)


def psi_map(
    L: _Lattice,
    primes: tuple[PrimeIdeal, ...],
) -> dict[int, int]:
    """psi : Spec(L) --> L, psi(p) = bigvee (L \\ p).

    The complement of a prime ideal in a finite lattice is a *prime
    filter*, hence non-empty (it contains top).  We take the join of all
    its elements, which is well defined because L is a lattice.
    """
    out: dict[int, int] = {}
    for i, p in enumerate(primes):
        complement = [a for a in L.elements if a not in p.members]
        if not complement:
            # p is the whole lattice; should never happen for a prime ideal
            out[i] = L.bottom
            continue
        acc = complement[0]
        for x in complement[1:]:
            acc = L.join[(acc, x)]
        out[i] = acc
    return out


def check_morphisms(
    L: _Lattice,
    topology: ZariskiTopology,
) -> dict[str, bool]:
    """Verify the bidirectional morphism axioms for (phi, psi)."""
    primes = topology.primes
    phi = phi_map(L, topology)
    psi = psi_map(L, primes)

    # Order preservation of phi: a <= b implies phi(a) subseteq phi(b)?
    # CAREFUL: D(a) = {p : a notin p}; if a <= b and a notin p then since p is
    # downward-closed b notin p too, so D(a) subseteq D(b).  Good.
    phi_op = True
    for a in L.elements:
        for b in L.elements:
            if L.is_le(a, b) and not (phi[a] <= phi[b]):
                phi_op = False
                break
        if not phi_op:
            break

    # Injectivity of phi (Stone separation): phi(a) = phi(b) implies a = b.
    phi_inj = True
    seen: dict[frozenset[int], int] = {}
    for a in L.elements:
        if phi[a] in seen and seen[phi[a]] != a:
            phi_inj = False
            break
        seen[phi[a]] = a

    # psi well defined (we built it as a total function above)
    psi_wd = all(i in psi for i in range(len(primes)))

    # Round-trip duality: for each prime p, phi(psi(p)) should reproduce p
    # in the sense that the basic open at psi(p) equals D-of-something
    # consistent with p.  In a finite distributive lattice this collapses
    # to phi being a lattice iso onto its image and psi a left inverse.
    duality = True
    for i, p in enumerate(primes):
        a = psi[i]
        # Test: for prime p, a in p iff a not in (L \\ p).  Since a is the
        # join of (L \\ p), and p is prime, a in p would force one of the
        # join-summands to be in p, contradiction.  So a notin p, i.e.
        # i in phi[a].
        if i not in phi[a]:
            duality = False
            break

    return {
        "phi_order_preserving": phi_op,
        "phi_injective": phi_inj,
        "psi_well_defined": psi_wd,
        "duality_holds": duality,
    }


# ---------------------------------------------------------------------------
# Top-level entry point
# ---------------------------------------------------------------------------

def compute_spectrum(ss: StateSpace) -> SpectrumResult:
    """Compute the prime ideal spectrum of a state space's lattice."""
    notes: list[str] = []
    try:
        L = _build_lattice(ss)
    except ValueError as e:
        return SpectrumResult(
            is_lattice=False,
            is_distributive=False,
            num_elements=0,
            num_ideals=0,
            num_prime_ideals=0,
            primes=(),
            topology=None,
            irreducible_components=(),
            phi_is_order_preserving=False,
            phi_is_injective=False,
            psi_is_well_defined=False,
            duality_holds=False,
            notes=(f"not a lattice: {e}",),
        )

    from reticulate.lattice import check_distributive  # noqa: WPS433
    dr = check_distributive(ss)

    ideals = enumerate_ideals(L)
    primes = enumerate_prime_ideals(L)
    topology = build_topology(L, primes)
    components = irreducible_components(L, topology)
    morph = check_morphisms(L, topology)

    if not dr.is_distributive:
        notes.append(
            "lattice is non-distributive; phi may fail to be a lattice "
            "homomorphism even when it remains order-preserving"
        )
    if len(components) > 1:
        notes.append(
            f"protocol decomposes into {len(components)} irreducible components"
        )

    return SpectrumResult(
        is_lattice=True,
        is_distributive=dr.is_distributive,
        num_elements=len(L.elements),
        num_ideals=len(ideals),
        num_prime_ideals=len(primes),
        primes=tuple(primes),
        topology=topology,
        irreducible_components=components,
        phi_is_order_preserving=morph["phi_order_preserving"],
        phi_is_injective=morph["phi_injective"],
        psi_is_well_defined=morph["psi_well_defined"],
        duality_holds=morph["duality_holds"],
        notes=tuple(notes),
    )


__all__ = [
    "PrimeIdeal",
    "ZariskiTopology",
    "SpectrumResult",
    "enumerate_ideals",
    "enumerate_prime_ideals",
    "build_topology",
    "irreducible_components",
    "phi_map",
    "psi_map",
    "check_morphisms",
    "compute_spectrum",
]
